name: CI-CD

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Super-Linter
        uses: github/super-linter@v4.10.1
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ci:
    name: Continues Integration
    runs-on: ubuntu-latest
    needs: [super-lint]
    strategy:
      matrix:
        node-version: [18.x, 16.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test